AllCops:
  DisplayCopNames:    true
  DisplayStyleGuide:  true
  StyleGuideCopsOnly: true
  TargetRubyVersion:  3.2
  SuggestExtensions: false

Metrics/LineLength:
  Max: 140

Documentation:
  Enabled: false

FrozenStringLiteralComment:
  Enabled: false

Style/FileName:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - spec/**/*_spec.rb